site_name: 정책과 절차

theme:
  name: material
  custom_dir: overrides
  favicon: ./assets/images/clip.png

nav:
    - 내규:
      # - 현행정관: index.md      
      - 90 품질관리규정: ./policy/90-품질관리규정.md   
      - 91 품질관리규정(부록): ./policy/91-품질관리규정(부록).md
      - 93 업무수임과 유지에 관한 Policy: ./policy/93-업무수임과 유지에 관한 Policy.md
    # - 정책 공지:
      # - TBD: index.md
    - 품질관리절차:
      - 계약: 'index.md'
      - 업무품질관리검토:
        - 외부감사법 감사업무: './qcProcedures/qualityReview.md'        
      - 발행: ./qcProcedures/goPublic.md
      - 업무의 수행:
        - 시간: ./qcProcedures/workingPaper.md
        - 조서: ./qcProcedures/workingPaper.md
        - 기타: ./qcProcedures/workingPaper.md
    - 관련 절차: ./qcProcedures/workingPaper.md

markdown_extensions:
    - toc:
        permalink: '#'
        baselevel: 1
        toc_depth: 2-6
    - attr_list
    - footnotes
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - md_in_html
  
plugins:
  - search
extra_javascript:
  - app.js
extra_css:
  - style.css
  